-- Seed data for Dimension Tables that aren't generated by Python or are static
-- Note: Most dimensions are generated via python/generate_data.py for realism.
-- This file serves as a template for manual seeding if needed.

-- Populating Date Dimension
INSERT INTO dim_dates (date_key, year, quarter, month, day, month_name, day_name, is_weekend)
SELECT
    datum AS date_key,
    EXTRACT(YEAR FROM datum) AS year,
    EXTRACT(QUARTER FROM datum) AS quarter,
    EXTRACT(MONTH FROM datum) AS month,
    EXTRACT(DAY FROM datum) AS day,
    TO_CHAR(datum, 'Month') AS month_name,
    TO_CHAR(datum, 'Day') AS day_name,
    CASE WHEN EXTRACT(ISODOW FROM datum) IN (6, 7) THEN TRUE ELSE FALSE END AS is_weekend
FROM generate_series('2021-01-01'::DATE, '2024-12-31'::DATE, '1 day'::INTERVAL) datum;
